spring.application.name=RAG-java

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=gemma4
spring.ai.ollama.chat.options.temperature=0.0
spring.ai.ollama.chat.options.num-ctx=4096
spring.ai.ollama.embedding.options.model=bge-m3
spring.ai.ollama.request-timeout=120s

# Qdrant
spring.ai.vectorstore.qdrant.url=http://localhost:6333
spring.ai.vectorstore.qdrant.collection-name=collection
spring.ai.vectorstore.qdrant.embedding-model=ollama
spring.ai.vectorstore.qdrant.api-key=your_secret_api_key_here
spring.ai.vectorstore.qdrant.use-tls=false
spring.ai.vectorstore.qdrant.initialize-schema=true